#!/usr/bin/env python3
"""
Extrator de Cookies para Publicação Automática

Este script abre o navegador para você fazer login manualmente nas plataformas
e salva os cookies para uso posterior na automação.

Uso:
    python extract_cookies.py tiktok
    python extract_cookies.py youtube
    python extract_cookies.py instagram
    python extract_cookies.py all
"""
import sys
import time
import json
import pickle
from pathlib import Path

# Tentar undetected_chromedriver primeiro, fallback para selenium
try:
    import undetected_chromedriver as uc
    USE_UNDETECTED = True
except ImportError:
    from selenium import webdriver
    from selenium.webdriver.chrome.service import Service
    from selenium.webdriver.chrome.options import Options
    from webdriver_manager.chrome import ChromeDriverManager
    USE_UNDETECTED = False

PLATFORMS = {
    "tiktok": {
        "url": "https://www.tiktok.com/login",
        "check_url": "tiktok.com",
        "logged_indicator": "/upload"
    },
    "youtube": {
        "url": "https://accounts.google.com/signin/v2/identifier?service=youtube",
        "check_url": "youtube.com",
        "logged_indicator": "studio.youtube.com"
    },
    "instagram": {
        "url": "https://www.instagram.com/accounts/login/",
        "check_url": "instagram.com",
        "logged_indicator": "instagram.com"
    }
}


def create_driver():
    """Cria driver com anti-detecção"""
    if USE_UNDETECTED:
        print("🛡️  Usando undetected-chromedriver (anti-detecção)")
        options = uc.ChromeOptions()
        options.add_argument("--start-maximized")
        driver = uc.Chrome(options=options)
    else:
        print("⚠️  Usando Selenium padrão (instale undetected-chromedriver para melhor resultado)")
        options = Options()
        options.add_argument("--start-maximized")
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)
    
    return driver


def save_cookies_netscape(driver, filepath: Path):
    """Salva cookies no formato Netscape (compatível com tiktok-uploader)"""
    cookies = driver.get_cookies()
    
    with open(filepath, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
        f.write("# This file was generated by AI Video Clipper Studio\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            # Netscape format: domain, flag, path, secure, expiry, name, value
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expiry = str(int(cookie.get('expiry', 0)))
            path = cookie.get('path', '/')
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
    
    print(f"   ✅ Cookies Netscape: {filepath}")


def save_cookies_pickle(driver, filepath: Path):
    """Salva cookies no formato pickle (backup)"""
    cookies = driver.get_cookies()
    with open(filepath, 'wb') as f:
        pickle.dump(cookies, f)
    print(f"   ✅ Cookies Pickle: {filepath}")


def save_cookies_json(driver, filepath: Path):
    """Salva cookies no formato JSON (legível)"""
    cookies = driver.get_cookies()
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(cookies, f, indent=2, ensure_ascii=False)
    print(f"   ✅ Cookies JSON: {filepath}")


def extract_cookies(platform: str):
    """Extrai cookies para uma plataforma específica"""
    if platform not in PLATFORMS:
        print(f"❌ Plataforma desconhecida: {platform}")
        print(f"   Opções: {', '.join(PLATFORMS.keys())}")
        return False
    
    config = PLATFORMS[platform]
    cookies_dir = Path("browser_profiles") / "cookies"
    cookies_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"\n{'=' * 60}")
    print(f"🔐 EXTRAÇÃO DE COOKIES - {platform.upper()}")
    print(f"{'=' * 60}")
    print(f"\n📋 Instruções:")
    print(f"   1. O navegador vai abrir em: {config['url']}")
    print(f"   2. Faça login com sua conta")
    print(f"   3. Após logado, digite 'salvar' no terminal")
    print(f"\n⏳ Abrindo navegador...")
    
    driver = create_driver()
    
    try:
        driver.get(config['url'])
        
        print(f"\n🌐 Navegador aberto!")
        print(f"📝 Faça login na sua conta {platform.upper()}")
        print(f"\n" + "-" * 40)
        
        while True:
            cmd = input("Digite 'salvar' quando estiver logado (ou 'sair' para cancelar): ").strip().lower()
            
            if cmd == 'sair':
                print("❌ Operação cancelada")
                return False
            
            if cmd == 'salvar':
                # Verificar se parece estar logado
                current_url = driver.current_url
                print(f"\n📍 URL atual: {current_url}")
                
                # Salvar cookies em 3 formatos
                print(f"\n💾 Salvando cookies...")
                base_name = platform
                
                save_cookies_netscape(driver, cookies_dir / f"{base_name}_cookies.txt")
                save_cookies_pickle(driver, cookies_dir / f"{base_name}_cookies.pkl")
                save_cookies_json(driver, cookies_dir / f"{base_name}_cookies.json")
                
                print(f"\n✅ Cookies salvos com sucesso para {platform.upper()}!")
                print(f"📁 Diretório: {cookies_dir.absolute()}")
                return True
                
    except Exception as e:
        print(f"❌ Erro: {e}")
        import traceback
        traceback.print_exc()
        return False
    finally:
        print("\n🛑 Fechando navegador...")
        try:
            driver.quit()
        except:
            pass


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print(f"\nPlataformas disponíveis: {', '.join(PLATFORMS.keys())}, all")
        sys.exit(1)
    
    platform = sys.argv[1].lower()
    
    if platform == 'all':
        for p in PLATFORMS:
            if not extract_cookies(p):
                print(f"⚠️  Falha em {p}, continuando...")
            print("\n")
    else:
        extract_cookies(platform)
    
    print("\n" + "=" * 60)
    print("🎉 EXTRAÇÃO DE COOKIES CONCLUÍDA!")
    print("=" * 60)
    print("\n📝 Próximos passos:")
    print("   1. Os cookies foram salvos em browser_profiles/cookies/")
    print("   2. Execute: python publish.py --video seu_video.mp4")
    print("   3. O sistema usará os cookies salvos automaticamente")
    print("")


if __name__ == "__main__":
    main()
